# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "bainisuoci"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 100

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "小目标":
        filters: ["small object detect", "sod", "tiny object detect", "tod"]
    "object detection":
        filters: ["object detect", "object detection"]
    "Remote Sensing Image":
        filters: ["object detect", "object detection","Remote Sensing Image Target Detection"]
    "Ship detection":
        filters: ["Ship detection"]
        

